[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "guantlet"
version = "0.0.1"
description = "Discord bot to create custom tourneys for ELO character ranking."
requires-python = ">=3.11"
dependencies = [
    "discord.py==2.4.0",
    "python-dotenv",
    "pydantic",
]

[project.optional-dependencies]
dev = [
    "black",  # Formatter
    "ruff",   # Linter
    "isort",  # Import sorter
]

[tool.setuptools.packages.find]
# where = ["."]
include = ["bot"]
# exclude = [".venv*", ".env*", "scripts", "build"]

[tool.black]
line-length = 88
